### PR TITLE
Factory chooses what surrenders

### PR DESCRIPTION
**Pull request by keepermanj**
If we let the factory choose what can surrender, then we shouldn't get any weird surprizes.

### CODE REVIEW

**Comment by miki151** [comment]
What weird surprises are there? I'd prefer for it to be defined organically
instead of adding another attribute.

**Comment by SoftMonster** [comment]
Zombies are questionable. The vampire lord would be nice.

**Comment by SoftMonster** [comment]
Might want to capture certain beasts in the future?

**Comment by keepermanj** [comment]
Your existing system works quite well, actually. In future beasts could be tamed rather than captured. The vampire lord has never been capturable for some reason. Zombies are fine, really. Feel free to close this item, if you don't want it.

**Comment by keepermanj** [comment]
Wood elves and driads have +25 archery. Too high to have in your dungeon? Also, doppleganger eats them.

**Pull request closed without merging**
