### PR TITLE
Effects doppleganger does not inherit

### PR DESCRIPTION
**Pull request by keepermanj**
eg. Collapsed effect isn't absorbable. Neither should a headless zombie make a doppleganger blind.
I have tried to future-proof it by defining all unabsorbable attributes.
A few other restrictions seem like a good idea. eg. Malee Resistance from knight prisoners, which is OP.

### CODE REVIEW

**Comment by miki151** [comment]
I think the desired solution is to make all intrinsic permanent effects, i.e. that are defined in creature_factory absorbable, and those that are buffs from equipment or effects of beheading be ignored.

**Comment by SoftMonster** [comment]
Hmm. Perhaps beheading and losing legs could use a calculation instead of making a lasting effect (which would get absorbed) ?

**Comment by SoftMonster** [comment]
Equipment is dropped when a creature is absorbed although there could be an issue. I didn't test that.

**Comment by miki151** [comment]
The other reason is that you can cheat by having the absorbed creature put on a ring to make the doppie inherit the effect. So it should really only inherit intrinsic effects. I will take care of this.

**Comment by SoftMonster** [comment]
Ok

**Comment by miki151** [comment]
Thinking about this some more, the doppie mechanics are already quite absurd, so maybe inheriting collapsed or blind state isn't that bad, and it does some job of balancing out the good effects.

I'm thinking that maybe omitting the equipment by dropping it first, as you mentioned, could solve the ring problem.

Then maybe to fix the balance in a major way we could make the doppies unhealable. So basically a one-time use super weapon.

What do you think? Would there be any leftover issues?

**Comment by SoftMonster** [comment]
You should probably absorb bad features as well as good, or else there are no real decisions to make.

If equipment is dropped before the monster is absorbed then it probably would solve that ring problem but I guess we would have to try it and see what happens.

An alternative to letting them slowly die of wounds could be to give them a "summoned time left" timer that is about 5000 turns or something before they return back to the spirit world.

The only other left over issue I know of is the infinite range on bows, which gives them huge advantage in a shoot-out.

**Pull request closed without merging**
