### PR TITLE
Prisoners from endless mode waves

### PR DESCRIPTION
**Pull request by keepermanj**
For endless mode.

### CODE REVIEW

**Comment by miki151** [comment]
I'm not sure this is going to work. The current wave needs to end when all attackers are either captured or dead. The way it is now it will only end and you'll get mana when you enslave them, which is weird.

**Comment by miki151** [comment]
I'll need to re-implement some stuff for this to work, as right now you also can't capture anyone who doesn't belong to any collective.

**Comment by keepermanj** [comment]
That might be why you can't take the vampire lord captive.

**Comment by keepermanj** [comment]
The code above takes possible prisoners from the wave as if it were a collective. Now that you mention it, I think there was a problem with not getting the mana as you say.

**Comment by keepermanj** [comment]
Code is redundant, as Michal has a better solution that works really well.

**Pull request closed without merging**
