### PR TITLE
Dark knight starts with iron working

### PR DESCRIPTION
**Pull request by keepermanj**
Take into consideration the type of keeper, when calculating the initial technology.

### CODE REVIEW

**Comment by keepermanj** [comment]
I thought there was something wrong when I tested it, but the penny didn't drop. When I looked at it again I realised that I needed to build bookcases, then when I clicked on the library I needed to research sorcery first. Then when I tried to research sorcery in the library, it sent me back to bookcases...

**Comment by SoftMonster** [comment]
The chicken-and-egg problem is fixed by the 2nd commit.

**Comment by keepermanj** [comment]
This code is out of date and superseded by Michal's new way of doing this, which also has modding support :)

**Comment by keepermanj** [comment]
This code is out of date and superseded by Michal's new way of doing this, which also has modding support :)

**Pull request closed without merging**
