### PR TITLE
Put traits in minion titles

### PR DESCRIPTION
**Pull request by keepermanj**
Examples:
Adrian the winged vampire
Lurburz the goblin (blacksmith)
Blind zombie

### CODE REVIEW

**Comment by keepermanj** [comment]
The first two commits cancel each other and can be merged and ignored.

**Comment by SoftMonster** [comment]
This could be achieved in Alpha 27 by changing creatures.txt instead of changing some code. I may close this pull request at some point.

**Comment by SoftMonster** [comment]
This code has really moved on. A much better solution is to allow a name change as a part of special traits in immigration.txt

**Comment by keepermanj** [comment]
Closing as outdated.

**Pull request closed without merging**
