### PR TITLE
Trap detection rings sometimes owned by new bandit tribe leaders

### PR DESCRIPTION
**Pull request by keepermanj**

### CODE REVIEW

**Comment by SoftMonster** [comment]
The lasting effect can also be used for trap detection potions if preferred.

**Comment by SoftMonster** [comment]
We would want an ordinary potion with a timer.

**Comment by miki151** [comment]
I'm not sure about this, bandits used to have trap detection and people
didn't like it, because they're one of the first villains you encounter.
Maybe some other villain could have trap detection?

**Comment by SoftMonster** [comment]
We could put it on a potion and make them randomly appear in chests.

**Comment by SoftMonster** [comment]
Gnomes or dwarves perhaps.

**Comment by SoftMonster** [comment]
The elementalist could have a ring.

**Comment by keepermanj** [comment]
Elementalist has it now. What do you think?

**Comment by SoftMonster** [comment]
Conflicting files can be fixed if required.

**Comment by keepermanj** [comment]
Trap detection rings can be given randomly to bandits by changing creature_inventory.txt if needed. This pull request is a lot of work for something that is 90% there. Closing pull request.

**Comment by keepermanj** [comment]
Closed

**Pull request closed without merging**
