### PR TITLE
Review iron cost of prisons

### PR DESCRIPTION
**Pull request by keepermanj**
It is a good time to review the cost of prisons.

### CODE REVIEW

**Comment by SoftMonster** [comment]
At the moment it is 5 iron for a prison. 10 iron for a prisoner. No cost in mana/population points either. Too cheap?

**Comment by SoftMonster** [comment]
Could put it up to 15 iron and require 6 prison squares to have the same effect.

**Comment by SoftMonster** [comment]
The prison squares could look a bit like cages.

**Comment by SoftMonster** [comment]
Perhaps prisoners need a torture table and a few cell tiles.

**Comment by keepermanj** [comment]
Cost of prisons is OK in latest code. Plays quite nicely. Will close.

**Pull request closed without merging**
